# Eureka Server URL (तुझ्या Eureka Service चा Railway URL)
eureka.client.service-url.defaultZone=https://quiz-eureka-production.up.railway.app/eureka/
# Railway वर hostname dynamic असतो, त्यामुळे prefer-ip-address false कर
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${HOSTNAME:localhost}

# Database (आता Railway च्या Internal MySQL ला Point कर)
# Database (Environment Variable precedence with fallback)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=true&requireSSL=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ocfQhwgIJxmePctZYjokngiWZVoOIruB}